# 服务端口
server:
  port: 8080

# 数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_academy_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

properties:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: '!QEJ%KUD$YE@LDF^'
    # 设置jwt过期时间,单位(秒)
    time-to-live: 86400
    # 设置前端传递过来的令牌名称
    token-name: "token"